// ============================================================================
// File Name   : blackwell_tma_mbarrier_top.sv
// Date        : 2026-08-27
// Description : Tensor-core baseline plus the complete TMA/mbarrier subsystem.
//
// Tensor and TMA use independent command channels. The caller observes TMA
// completion before issuing Tensor commands which consume the copied data.
// ============================================================================

`default_nettype none

module blackwell_tma_mbarrier_top #(
    parameter int unsigned BAR_ASYNC_ENTRIES = 16,
    parameter int unsigned TMEM_BANKS          = 8,
    parameter int unsigned TMEM_BASE_DEPTH     = 128,
    parameter int unsigned STAGING_DEPTH       = 2,
    parameter int unsigned TC_REG_SLICE        = 1,
    parameter int unsigned TMEM_PORT_MODE      = 0,
    parameter int unsigned SMEM_READ_PORTS     = 2,
    parameter int unsigned CMD_QUEUE_DEPTH     = 8,
    parameter int unsigned DESC_CACHE_ENTRIES  = 4,
    parameter int unsigned MSHR_ENTRIES        = 16,
    parameter int unsigned BAR_CACHE_ENTRIES   = 4,
    parameter int unsigned WAIT_ENTRIES        = 32,
    parameter int unsigned WRITE_BUF_DEPTH     = 8,
    parameter int unsigned BAR_CLOCK_PERIOD_NS = 10,
    parameter int unsigned BAR_WAIT_DEFAULT_CYCLES = 64
) (

    input tma_mbarrier_pkg::tma_cmd_t tma_cmd_i,
    output tma_mbarrier_pkg::tma_rsp_t tma_rsp_o,
    output tma_mbarrier_pkg::bw_mem_attr_t gmem_req_attr_o,
    output tma_mbarrier_pkg::bw_mem_attr_t smem_req_attr_o,
    output wire tma_order_req_vld_o,
    input wire tma_order_req_rdy_i,
    output tma_mbarrier_pkg::bw_order_req_t tma_order_req_o,
    input wire tma_order_rsp_vld_i,
    output wire tma_order_rsp_rdy_o,
    input tma_mbarrier_pkg::bw_order_rsp_t tma_order_rsp_i,


    input wire tc_arrive_vld_i,
    output wire tc_arrive_rdy_o,
    input tma_mbarrier_pkg::bar_cmd_t tc_arrive_i,
    output wire tc_arrive_rsp_vld_o,
    input wire tc_arrive_rsp_rdy_i,
    output tma_mbarrier_pkg::bar_rsp_t tc_arrive_rsp_o,
    input tma_mbarrier_pkg::bar_cmd_t bar_cmd_i,
    output tma_mbarrier_pkg::bar_rsp_t bar_rsp_o,
    input wire async_cpl_req_vld_i,
    output wire async_cpl_req_rdy_o,
    input tma_mbarrier_pkg::bw_async_req_t async_cpl_req_i,
    input wire async_req_vld_i,
    output wire async_req_rdy_o,
    input tma_mbarrier_pkg::bw_async_req_t async_req_i,
    output wire async_rsp_vld_o,
    input wire async_rsp_rdy_i,
    output tma_mbarrier_pkg::bw_async_rsp_t async_rsp_o,
    input wire report_req_vld_i,
    output wire report_req_rdy_o,
    input tma_mbarrier_pkg::bar_report_req_t report_req_i,
    output wire report_rsp_vld_o,
    input wire report_rsp_rdy_i,
    output tma_mbarrier_pkg::bar_rsp_t report_rsp_o,
    output wire bar_order_req_vld_o,
    input wire bar_order_req_rdy_i,
    output tma_mbarrier_pkg::bw_order_req_t bar_order_req_o,
    input wire bar_order_rsp_vld_i,
    output wire bar_order_rsp_rdy_o,
    input tma_mbarrier_pkg::bw_order_rsp_t bar_order_rsp_i,


    input  wire          clk,
    input  wire          rst_n,

    input  wire          cmd_vld_i,
    output wire          cmd_rdy_o,
    input  wire [2:0]    cmd_opcode_i,
    input  wire [15:0]   cmd_tag_i,
    input  wire [31:0]   cmd_a_base_i,
    input  wire [31:0]   cmd_b_base_i,
    input  wire [31:0]   cmd_dst_base_i,
    input  wire          cmd_tile_slot_i,
    input  wire          cmd_accumulate_i,
    input  wire [15:0]   cmd_wait_token_i,
    output wire          completion_vld_o,
    input  wire          completion_rdy_i,
    output wire [15:0]   completion_tag_o,
    output wire [2:0]    completion_opcode_o,
    output wire [7:0]    completion_status_o,
    output wire [15:0]   completion_token_o,

    output wire          smem_a_req_vld_o,
    input  wire          smem_a_req_rdy_i,
    output wire [31:0]   smem_a_req_addr_o,
    output wire [3:0]    smem_a_req_source_o,
    input  wire          smem_a_rsp_vld_i,
    output wire          smem_a_rsp_rdy_o,
    input  wire [255:0]  smem_a_rsp_data_i,
    input  wire [3:0]    smem_a_rsp_source_i,
    input  wire [1:0]    smem_a_rsp_status_i,
    output wire          smem_b_req_vld_o,
    input  wire          smem_b_req_rdy_i,
    output wire [31:0]   smem_b_req_addr_o,
    output wire [3:0]    smem_b_req_source_o,
    input  wire          smem_b_rsp_vld_i,
    output wire          smem_b_rsp_rdy_o,
    input  wire [255:0]  smem_b_rsp_data_i,
    input  wire [3:0]    smem_b_rsp_source_i,
    input  wire [1:0]    smem_b_rsp_status_i,
    output wire          smem_wr_req_vld_o,
    input  wire          smem_wr_req_rdy_i,
    output wire [31:0]   smem_wr_req_addr_o,
    output wire [255:0]  smem_wr_req_data_o,
    output wire [31:0]   smem_wr_req_mask_o,
    output wire [3:0]    smem_wr_req_source_o,
    input  wire          smem_wr_rsp_vld_i,
    output wire          smem_wr_rsp_rdy_o,
    input  wire [3:0]    smem_wr_rsp_source_i,
    input  wire [1:0]    smem_wr_rsp_status_i,

    input  wire          tma_cmd_vld_i,
    output wire          tma_cmd_rdy_o,

    output wire          tma_rsp_vld_o,
    input  wire          tma_rsp_rdy_i,

    input  wire          bar_cmd_vld_i,
    output wire          bar_cmd_rdy_o,

    output wire          bar_rsp_vld_o,
    input  wire          bar_rsp_rdy_i,

    output wire          gmem_req_vld_o,
    input  wire          gmem_req_rdy_i,
    output wire          gmem_req_write_o,
    output wire [63:0]   gmem_req_addr_o,
    output wire [1023:0] gmem_req_data_o,
    output wire [127:0]  gmem_req_mask_o,
    output wire [4:0]    gmem_req_id_o,
    input  wire          gmem_rsp_vld_i,
    output wire          gmem_rsp_rdy_o,
    input  wire [1023:0] gmem_rsp_data_i,
    input  wire [1:0]    gmem_rsp_status_i,
    input  wire [4:0]    gmem_rsp_id_i,
    output wire          tma_smem_req_vld_o,
    input  wire          tma_smem_req_rdy_i,
    output wire          tma_smem_req_write_o,
    output wire [31:0]   tma_smem_req_addr_o,
    output wire [255:0]  tma_smem_req_data_o,
    output wire [31:0]   tma_smem_req_mask_o,
    output wire [5:0]    tma_smem_req_id_o,
    input  wire          tma_smem_rsp_vld_i,
    output wire          tma_smem_rsp_rdy_o,
    input  wire [255:0]  tma_smem_rsp_data_i,
    input  wire [1:0]    tma_smem_rsp_status_i,
    input  wire [5:0]    tma_smem_rsp_id_i,

    input  wire          perf_clear_i,
    output wire [31:0]   perf_smem_stall_o,
    output wire [31:0]   perf_tc_busy_o,
    output wire [31:0]   perf_tmem_conflict_o,
    output wire [31:0]   perf_tmem_stall_o,
    output wire [31:0]   perf_writeback_stall_o,
    output wire [31:0]   perf_issued_o,
    output wire [31:0]   perf_completed_o
);

    import tma_mbarrier_pkg::*;

    blackwell_tensor_subsystem #(
        .TMEM_BANKS      (TMEM_BANKS),
        .TMEM_BASE_DEPTH (TMEM_BASE_DEPTH),
        .STAGING_DEPTH   (STAGING_DEPTH),
        .TC_REG_SLICE    (TC_REG_SLICE),
        .TMEM_PORT_MODE  (TMEM_PORT_MODE),
        .SMEM_READ_PORTS (SMEM_READ_PORTS)
    ) u_tensor_subsystem (.*);

    tma_mbarrier_subsystem #(
        .BAR_ASYNC_ENTRIES(BAR_ASYNC_ENTRIES),
        .CMD_QUEUE_DEPTH    (CMD_QUEUE_DEPTH),
        .DESC_CACHE_ENTRIES (DESC_CACHE_ENTRIES),
        .MSHR_ENTRIES       (MSHR_ENTRIES),
        .BAR_CACHE_ENTRIES  (BAR_CACHE_ENTRIES),
        .WAIT_ENTRIES       (WAIT_ENTRIES),
        .WRITE_BUF_DEPTH    (WRITE_BUF_DEPTH),
        .BAR_CLOCK_PERIOD_NS (BAR_CLOCK_PERIOD_NS),
        .BAR_WAIT_DEFAULT_CYCLES (BAR_WAIT_DEFAULT_CYCLES)
    ) u_tma_mbarrier (
        .clk                    (clk),
        .rst_n                  (rst_n),

        .tma_cmd_i(tma_cmd_i),
        .gmem_req_attr_o(gmem_req_attr_o),
        .tma_order_req_vld_o(tma_order_req_vld_o),
        .tma_order_req_rdy_i(tma_order_req_rdy_i),
        .tma_order_req_o(tma_order_req_o),
        .tma_order_rsp_vld_i(tma_order_rsp_vld_i),
        .tma_order_rsp_rdy_o(tma_order_rsp_rdy_o),
        .tma_order_rsp_i(tma_order_rsp_i),
        .smem_req_attr_o(smem_req_attr_o),

        .tma_cmd_vld_i(tma_cmd_vld_i),
        .tma_cmd_rdy_o(tma_cmd_rdy_o),

        .tma_rsp_o(tma_rsp_o),
        .tma_rsp_vld_o(tma_rsp_vld_o),
        .tma_rsp_rdy_i(tma_rsp_rdy_i),

        .async_cpl_req_vld_i(async_cpl_req_vld_i), .async_cpl_req_rdy_o(async_cpl_req_rdy_o),
        .async_cpl_req_i(async_cpl_req_i), .async_req_vld_i(async_req_vld_i),
        .async_req_rdy_o(async_req_rdy_o),
        .async_req_i(async_req_i),
        .async_rsp_vld_o(async_rsp_vld_o),
        .async_rsp_rdy_i(async_rsp_rdy_i),
        .async_rsp_o(async_rsp_o),
        .report_req_vld_i(report_req_vld_i),
        .report_req_rdy_o(report_req_rdy_o),
        .report_req_i(report_req_i),
        .report_rsp_vld_o(report_rsp_vld_o),
        .report_rsp_rdy_i(report_rsp_rdy_i),
        .report_rsp_o(report_rsp_o),
        .bar_order_req_vld_o(bar_order_req_vld_o),
        .bar_order_req_rdy_i(bar_order_req_rdy_i),
        .bar_order_req_o(bar_order_req_o),
        .bar_order_rsp_vld_i(bar_order_rsp_vld_i),
        .bar_order_rsp_rdy_o(bar_order_rsp_rdy_o),
        .bar_order_rsp_i(bar_order_rsp_i),
        .tc_arrive_vld_i(tc_arrive_vld_i), .tc_arrive_rdy_o(tc_arrive_rdy_o),
        .tc_arrive_i(tc_arrive_i), .tc_arrive_rsp_vld_o(tc_arrive_rsp_vld_o),
        .tc_arrive_rsp_rdy_i(tc_arrive_rsp_rdy_i), .tc_arrive_rsp_o(tc_arrive_rsp_o),
        .bar_cmd_i(bar_cmd_i), .bar_rsp_o(bar_rsp_o),
        .bar_cmd_vld_i          (bar_cmd_vld_i),
        .bar_cmd_rdy_o          (bar_cmd_rdy_o),

        .bar_rsp_vld_o          (bar_rsp_vld_o),
        .bar_rsp_rdy_i          (bar_rsp_rdy_i),

        .gmem_req_vld_o         (gmem_req_vld_o),
        .gmem_req_rdy_i         (gmem_req_rdy_i),
        .gmem_req_write_o       (gmem_req_write_o),
        .gmem_req_addr_o        (gmem_req_addr_o),
        .gmem_req_data_o        (gmem_req_data_o),
        .gmem_req_mask_o        (gmem_req_mask_o),
        .gmem_req_id_o          (gmem_req_id_o),
        .gmem_rsp_vld_i         (gmem_rsp_vld_i),
        .gmem_rsp_rdy_o         (gmem_rsp_rdy_o),
        .gmem_rsp_data_i        (gmem_rsp_data_i),
        .gmem_rsp_status_i      (gmem_rsp_status_i),
        .gmem_rsp_id_i          (gmem_rsp_id_i),
        .smem_req_vld_o         (tma_smem_req_vld_o),
        .smem_req_rdy_i         (tma_smem_req_rdy_i),
        .smem_req_write_o       (tma_smem_req_write_o),
        .smem_req_addr_o        (tma_smem_req_addr_o),
        .smem_req_data_o        (tma_smem_req_data_o),
        .smem_req_mask_o        (tma_smem_req_mask_o),
        .smem_req_id_o          (tma_smem_req_id_o),
        .smem_rsp_vld_i         (tma_smem_rsp_vld_i),
        .smem_rsp_rdy_o         (tma_smem_rsp_rdy_o),
        .smem_rsp_data_i        (tma_smem_rsp_data_i),
        .smem_rsp_status_i      (tma_smem_rsp_status_i),
        .smem_rsp_id_i          (tma_smem_rsp_id_i)
    );

endmodule

`default_nettype wire
